services:
  # auth_app:
  #   container_name: auth_app
  #   image: auth_app
  #   depends_on:
  #     - db
  #   environment:
  #     REAL_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
  #     APP_PORT: "8000"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - custom  
  db:
    container_name: 'db'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5431:5432"
    networks:
      - custom
  db_test:
    container_name: 'db_test'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge
