services:
  db:
    container_name: 'db'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5431:5432"
    networks:
      - custom
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 10s
     retries: 5
     start_period: 10s
  auth_app:
    container_name: auth_app
    image: auth_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      REAL_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
      APP_PORT: "8000"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom  
    volumes:
      - .:/app
    working_dir: /app

networks:
  custom:
    driver: bridge
  
volumes:
  postgres_data:
