"""Add rating and count of borrowed books to user model

Revision ID: 4458d672e7c0
Revises: a22cc36ccad6
Create Date: 2025-05-04 20:44:16.891958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4458d672e7c0'
down_revision = 'a22cc36ccad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('count_of_borrowed_books', sa.Integer(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'count_of_borrowed_books')
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
